### ISSUE TITLE
lcd_rotate is not being picked up by config.txt

### ISSUE THREAD

**Issue by puccaso** [TheRemote/Ubuntu-Server-raspi4-unofficial#1]
hello,

 im trying your image, (thanks btw, boots perfectly) however
i cannot get the Official 7" LCD display to rotate 180.

i'd normally use

lcd_rotate=2 in the config.txt
i tried adding
256 of gpu mem too, but no luck

any reason why the config.txt isn't being read?

**Comment by puccaso** [comment]
ok, 
the official config.txt was in the /boot/firmware folder
found it now

thanks again!

**Comment by TheRemote** [comment]
Thanks!
