### ISSUE TITLE
Screen resolution

### ISSUE THREAD

**Issue by olevenets2** [TheRemote/Ubuntu-Server-raspi4-unofficial#100]
Hi, I am using an old Samtron 76DF CRT monitor. Ubuntu determines the working screen resolution is not correct due to which the image is slightly distorted. I found the correct refresh rate for my monitor using xrandr, but this does not work for the gdm login manager and tty consoles. Maybe I need to generate my xorg.conf, but I ran into a systemd-logind problem which prevents me from creating a script. Maybe can make the monitor issue the correct edid, but how to do it?

**Comment by TheRemote** [comment]
Hey olevenets,

I would try the options in /boot/config.txt or /boot/firmware/config.txt inside Ubuntu.  There are a lot of config.txt options to adjust screen output/refresh rate/resolution/etc.

Let me know if you need further assistance!
