### ISSUE TITLE
[Question] Will switching the Arch to 32bit break the image

### ISSUE THREAD

**Issue by xdovahkinx** [TheRemote/Ubuntu-Server-raspi4-unofficial#102]
I'm planning on using this image to set up a custom emulation station (via Lutris, using several specific emus for a spread of consoles). I know for a fact that PCSX2 Is going to try and replace the arch to 32bit. (It doesn't like to run in 64bit for whatever reason when I tested it on my main PC running Std Ubuntu Desktop 18.04 LTS. 

I for obvious reasons did not want it to totally switch all my stuff to 32bit on my main machine which definitely benefits from x64. My worry and where this question originates from;

If I allow it to switch the libs/arch to what it requests, will this break this image?

(My concern is that I am pretty sure this image is x64, and I'm rather novice at this stuff)

Thanks in advance for the support!

**Comment by TheRemote** [comment]
Hey xdovahkinx,
Sorry for the slow response.  The userland in this image is all 64 bit as well as opposed to just the kernel, so it will definitely break the image!
