### ISSUE TITLE
Video Resolution

### ISSUE THREAD

**Issue by antonical** [TheRemote/Ubuntu-Server-raspi4-unofficial#104]
I have just tried the Desktop image V26 but it only boots as 720p and there no options for 1920x1080.

How can I force the rpi4 to use full hd resolution. This particular monitor is 1080i not 1080p.

If I boot it using the new Ubuntu 19.10 image and install the ubuntu desktop it boots fine in 1920x1080 but as you are probably aware there is no accelerated graphics.

ANy help appreciated.

Cheers
Tony

**Comment by TheRemote** [comment]
Can you try with v28?

**Comment by pranavburnwal** [comment]
V28 has the same issue.

**Comment by sd3326852** [comment]
Hi, I changed the video resolution to 1920x1080 via raspi-config , you can also try it .
