### ISSUE TITLE
Question: Changing pi4 after first boot, doesn't boot?

### ISSUE THREAD

**Issue by petritoast** [TheRemote/Ubuntu-Server-raspi4-unofficial#108]
After first boot using this image and changing the password, if I place the sdcard in a different pi4, it doesn't boot/connect over ssh? I am running it headless (don't have mini-hdmi cable on hand), so I don't know the exact error it might be reporting. Is this expected behavior?

**Comment by TheRemote** [comment]
Can you try with v28?

**Comment by petritoast** [comment]
Yes! It is working fine now with v28. Tried it with one 2GB and another 4GB pi4. What was changed to make it work? I see the changelog has something about ssh keys.

Thanks for the fix.
