### ISSUE TITLE
Long hang on Network Config

### ISSUE THREAD

**Issue by tgwaste** [TheRemote/Ubuntu-Server-raspi4-unofficial#113]
Hi,
  This happens on every boot and takes a while to get through.  Any ideas how to either avoid this or speed it up?
![IMG_2475](https://user-images.githubusercontent.com/690918/74208020-24118500-4c3f-11ea-8fad-83aa441b3bd2.jpeg)

**Comment by boxer911** [comment]
Try this. It worked for me;

$ systemctl mask systemd-networkd-wait-online.service


https://jrs-s.net/2018/06/17/wait-for-network-to-be-configured-no-limit/
