### ISSUE TITLE
Ubuntu released 18.04.4 with kernel 5.3 officially for RPi4

### ISSUE THREAD

**Issue by FPSychotic** [TheRemote/Ubuntu-Server-raspi4-unofficial#114]
Hi, congrats by your work.
just was released the official ubuntu image of 18.04.4 server with kernel 5.3. It is possible take a look and add all the features of your build and keep 5.3 kernel?. Ubuntu mate would be great as desktop. 
Could be great a tutorial how make a personalized build as you did. 
im interested on 5.3 kernel because RPi4 have serious issues of USB physical ID addresing with many UsB dispositives, as Realsenses d435,t265 (the most),kinect v1 and kinect v2 making very very hard use it for robotics, and for that reason I would like test the 5.3 kernel. I couldnt get show picture on my tvs properly, but still I got install Ubuntu mate desktop
thanks

**Comment by TheRemote** [comment]
Hey FPSychotic,

It should be possible to switch between kernels if you update to the main distro!
