### ISSUE TITLE
Pi wifi dropped when cable pull out

### ISSUE THREAD

**Issue by LFZ1994** [TheRemote/Ubuntu-Server-raspi4-unofficial#123]
I use eht cable connect to my pi4,ssh login pi,use netpaln to config my wifi,after edit netplan yaml file and reboot,everything is ok,wifi can connect to my router，but when I pull out cable,wifi dropped，even reboot pi,I still can not connect to my router when cable not insert；anyone have this problem or any suggestion

**Comment by TheRemote** [comment]
This is a netplan issue with Ubuntu -- it is possible to fix this in netplan -- check the documentation related to dual connections / this issue for more information!
