### ISSUE TITLE
Is this still required given official ubuntu server is available?

### ISSUE THREAD

**Issue by bugsyb** [TheRemote/Ubuntu-Server-raspi4-unofficial#129]
Noobie in pi4 world hence maybe silly question, but is this still anyhow better than official Ubuntu pi4 prepared images?
https://cdimage.ubuntu.com/releases/20.04.1/release/ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz

What is missing in the official one?
My guess is that maybe:
a) raspi-config
b) acceleration - not sure about this.

Any advises are more than welcome.

I haven't seen this also updated since Feb'19 hence even more doubts.

Thank you.

**Comment by TheRemote** [comment]
Hey bugsyb,

People are using it for different reasons but probably the main thing it can do is boot from USB mass storage on a Raspberry Pi 4.  I actually committed the tool to make it bootable to this repository as "BootFix.sh"

Ubuntu 20.04 / 20.10 are officially supported on the Pi now aside from that limitation and I'm sure that will be fixed eventually.  If you want to see a writeup about BootFix.sh and USB mass storage device booting with Ubuntu 20.04 / 20.10 check out https://jamesachambers.com/raspberry-pi-4-ubuntu-20-04-usb-mass-storage-boot-guide/.
