### ISSUE TITLE
Is zcat decompress doing anything??

### ISSUE THREAD

**Issue by jradxl** [TheRemote/Ubuntu-Server-raspi4-unofficial#132]
I dont think this is doing anything but just copying file
zcat -qf "$mntBoot/vmlinuz" > "$mntBoot/vmlinux"

I do a binary compare, and look at file size, and they are the same.

And the last post in this says decompressing isn't needed for Rp4

`https://askubuntu.com/questions/1312054/best-way-to-manual-decompress-kernel-ubuntu`

**Comment by TheRemote** [comment]
That is certainly possible.  I think the reason I did this is that either the example I based this off was compressed or that the kernel could be compressed on certain flavors (Mate maybe?).  

At any rate this could probably be tested and if still true eliminated for sure!
