### ISSUE TITLE
Feature request - USB C - USB gadget

### ISSUE THREAD

**Issue by Chick92** [TheRemote/Ubuntu-Server-raspi4-unofficial#134]
Awesome work! 

Would it be possible to implement us gadget, similar to https://www.hardill.me.uk/wordpress/2019/11/02/pi4-usb-c-gadget/ ?

I've tried myself for a day or so and had no luck. Got the interface to come up, but no IP address. Your help would be awesome!

Thanks again.

**Comment by TheRemote** [comment]
I'd love it, but probably not in this project since it's fairly obsolete at this point!

I do have something to point you to which is [P4wnP1](https://github.com/RoganDawes/P4wnP1).  This is a gadget mode device using the Raspberry Pi that may be of some interest!
