### ISSUE TITLE
Am I didn't understand something? May be 20.04.2 already can be boot much easier? 

### ISSUE THREAD

**Issue by JerryCauser** [TheRemote/Ubuntu-Server-raspi4-unofficial#135]
I didn't found your tutorial when I faced that problem with booting from USB and solved it just by patching EEPROM from Raspberry Imager and by replacing one line in config.txt
```
kernel=vmlinuz
```
Thats all. And everything works. 

whole my config.txt
```
[pi4]
max_framebuffers=2
arm_freq=2000
over_voltage=6

[all]
kernel=vmlinuz
arm_64bit=1
# device_tree_address=0x03000000

cmdline=cmdline.txt
include syscfg.txt
include usercfg.txt

initramfs initrd.img followkernel
```

May be I do not understand something and my system didn't work properly?

**Comment by TheRemote** [comment]
Yes, this is correct.  The image was finally fixed on 20.04.2!  

You just need to make sure you have the latest Raspberry Pi firmware.  I have [a guide on how to update this here](https://jamesachambers.com/raspberry-pi-4-bootloader-firmware-updating-recovery-guide/).  

The BootFix.sh is no longer necessary for Ubuntu as of 20.04.2 forward.  Thanks for posting this!
