### ISSUE TITLE
Raspberry Pi Powers off on first (every) boot

### ISSUE THREAD

**Issue by ghost** [TheRemote/Ubuntu-Server-raspi4-unofficial#136]
I ran BootFix.sh for a new Ubuntu server install (20.04.3), everything completed.  After removing the SD card and allowing it to boot from the USB drive, I get en error ("Failed to start Command from Kernel Command Line.") and then it powers off.

![IMG_3739](https://user-images.githubusercontent.com/16406596/149583076-81eaf74e-5c0a-4fb8-8beb-ce40679f3984.jpg)

**Comment by TheRemote** [comment]
Hello,

You need a firmware update for Ubuntu for this to work.  I [have instructions on how to do this here](https://jamesachambers.com/raspberry-pi-4-bootloader-firmware-updating-recovery-guide/).  Thanks!
