### ISSUE TITLE
Darwin support (MacOS)

### ISSUE THREAD

**Issue by samip5** [TheRemote/Ubuntu-Server-raspi4-unofficial#138]
Maybe this script could be tweaked so that it could work on Darwin too?

Darwin doesn't have /mnt for one. :)

**Comment by TheRemote** [comment]
So on Darwin this process is no longer necessary as long as you have [the latest Raspberry Pi firmware updates](https://jamesachambers.com/raspberry-pi-4-bootloader-firmware-updating-recovery-guide/).  Hopefully that helps!
