### ISSUE TITLE
higher display resolutions

### ISSUE THREAD

**Issue by nikchis** [TheRemote/Ubuntu-Server-raspi4-unofficial#20]
Is it possible to run resolution higher than 1920x1080 ?
My monitor is 21:9 ~ 2560x1080, xubuntu

**Comment by damarshall** [comment]
nikchris - you can control this via settings in _/boot/config.txt_
See the documentation here: [RPi config.txt video doc page](https://www.raspberrypi.org/documentation/configuration/config-txt/video.md)

so:
hdmi_group=2
hdmi_mode=xx  where xx is a value from the table on the doc page above.

**Comment by TheRemote** [comment]
Thanks damarshall!

**Comment by nikchis** [comment]
thank you @damarshall

**Comment by johnjelinek** [comment]
@damarshall: this doesn't seem to have any effect with 4k resolutions. Any idea how to display 4k?
