### ISSUE TITLE
Add CONFIG_CGROUP_PIDS=y?

### ISSUE THREAD

**Issue by HowellBP** [TheRemote/Ubuntu-Server-raspi4-unofficial#21]
Per https://github.com/teamserverless/k8s-on-raspbian/issues/16#issuecomment-493778276

I'm experimenting with a [microk8s](microk8s.io) setup on a Pi4 4GB and am running into an error due to the aforementioned flag not being set. Is there a way to set this during compile time, or otherwise inject it into whatever the Ubuntu sub for arch/arm/configs/bcmrpi_defconfig is before compile?

**Comment by TheRemote** [comment]
Yes sir, I will add this in the image

**Comment by TheRemote** [comment]
Added in v8
