### ISSUE TITLE
sudo commands taking a long time to execute - /etc/hosts issue

### ISSUE THREAD

**Issue by petritoast** [TheRemote/Ubuntu-Server-raspi4-unofficial#22]
sudo commands take more than 10secs to start executing. Problem seems to be related to hostname. Adding '127.0.0.1 ubuntu' to /etc/hosts fixed this easily, but maybe add this to the next release.

Ref: https://askubuntu.com/a/458057

**Comment by TheRemote** [comment]
Added in v8
