### ISSUE TITLE
CephFS (kernel module) is missing

### ISSUE THREAD

**Issue by wasurerarenai** [TheRemote/Ubuntu-Server-raspi4-unofficial#25]
Similar to Issue #9 , I'm looking to have the "ceph" module included, to support kernel-side mounting of CephFS filesystems (instead of RBD block devices). This is to help integrate a few Rasberry Pi 4 nodes into a Proxmox VE environment with CephFS as a storage backend.

```
ubuntu@ubuntu:~$ sudo modprobe ceph
modprobe: FATAL: Module ceph not found in directory /lib/modules/4.19.71-v8+
```

Documentation:
https://docs.ceph.com/docs/master/cephfs/kernel/
https://docs.ceph.com/docs/master/cephfs/kernel-features/

Kernel module dependencies:
```
root@proxmox:~$ lsmod | grep ceph
ceph                  385024  1
libceph               323584  1 ceph
fscache               368640  1 ceph
libcrc32c              16384  6 nf_conntrack,nf_nat,btrfs,libceph,ip_vs,sctp
```

The Proxmox kernel config:
```
root@proxmox:~$ grep -E '^CONFIG_CEPH|^CONFIG_FSCACHE|^CONFIG_LIBCRC32C' /boot/config-5.0.21-2-pve | grep -v '^#' | sort
CONFIG_CEPH_FSCACHE=y
CONFIG_CEPH_FS=m
CONFIG_CEPH_FS_POSIX_ACL=y
CONFIG_CEPH_LIB=m
CONFIG_CEPH_LIB_USE_DNS_RESOLVER=y
CONFIG_FSCACHE=m
CONFIG_FSCACHE_STATS=y
CONFIG_LIBCRC32C=m
```

**Comment by TheRemote** [comment]
Can you try with v9?
