### ISSUE TITLE
Mistake in build script

### ISSUE THREAD

**Issue by wtarreau** [TheRemote/Ubuntu-Server-raspi4-unofficial#26]
Hi,

you have a small mistake in the build script, you copy the kernel (arm64/boot/Image) to the initrd image. I think you wanted to call it kernel.img-$VERSION instead, or maybe it's a leftover from a previous script since you already copy the kernel a few lines above anyway. It's harmless, just takes 12 extra MB and is confusing since it's not an initrd!

https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial/blob/41d106b819a44b53260fcc92a4e810190bb99ecc/BuildPiKernel64bit.sh#L127

**Comment by TheRemote** [comment]
Thanks, this has been fixed in the latest merge!
