### ISSUE TITLE
lm-sensors doesn't work, which can't read CPU temperature

### ISSUE THREAD

**Issue by KatyushaScarlet** [TheRemote/Ubuntu-Server-raspi4-unofficial#27]
System Version:Pre-Release v7

lm-sensors is already the newest version (1:3.4.0-4).
root@pi:~# sensors
No sensors found!
Make sure you loaded all the kernel drivers you need.
Try sensors-detect to find out which these are.

**Comment by bruces22** [comment]
Same issue with V8...

**Comment by efrasyad** [comment]
any reason you're not using vcgencmd if you need to measure cpu temp?

`vcgencmd measure_temp `

This is RPI4

> mercury:~# sensors-detect
> # sensors-detect revision 6284 (2015-05-31 14:00:33 +0200)
> # Kernel: 4.19.67-v8+ aarch64
> # Processor:  (//)
> 
> This program will help you determine which kernel modules you need
> to load to use lm_sensors most effectively. It is generally safe
> and recommended to accept the default answers to all questions,
> unless you know what you're doing.
> 
> Some south bridges, CPUs or memory controllers contain embedded sensors.
> Do you want to scan for them? This is totally safe. (YES/no): yes
> modprobe: FATAL: Module cpuid not found in directory /lib/modules/4.19.67-v8+
> Failed to load module cpuid.
> Silicon Integrated Systems SIS5595...                       No
> VIA VT82C686 Integrated Sensors...                          No
> VIA VT8231 Integrated Sensors...                            No
> AMD K8 thermal sensors...                                   No
> AMD Family 10h thermal sensors...                           No
> AMD Family 11h thermal sensors...                           No
> AMD Family 12h and 14h thermal sensors...                   No
> AMD Family 15h thermal sensors...                           No
> AMD Family 16h thermal sensors...                           No
> AMD Family 15h power sensors...                             No
> AMD Family 16h power sensors...                             No
> Intel digital thermal sensor...                             No
> Intel AMB FB-DIMM thermal sensor...                         No
> Intel 5500/5520/X58 thermal sensor...                       No
> VIA C7 thermal sensor...                                    No
> VIA Nano thermal sensor...                                  No
> 
> Lastly, we can probe the I2C/SMBus adapters for connected hardware
> monitoring devices. This is the most risky part, and while it works
> reasonably well on most systems, it has been reported to cause trouble
> on some systems.
> Do you want to probe the I2C/SMBus adapters now? (YES/no): yes
> Sorry, no supported PCI bus adapters found.
> Module i2c-dev loaded successfully.
> 
> Sorry, no sensors were detected.
> Either your system has no sensors, or they are not supported, or
> they are connected to an I2C or SMBus adapter that is not
> supported. If you find out what chips are on your board, check
> http://www.lm-sensors.org/wiki/Devices for driver status.
> 

And this is RPI3

> ns1:~$ sudo sensors-detect
> # sensors-detect revision 6284 (2015-05-31 14:00:33 +0200)
> # Kernel: 4.15.0-1048-raspi2 aarch64
> # Processor:  (//)
> 
> This program will help you determine which kernel modules you need
> to load to use lm_sensors most effectively. It is generally safe
> and recommended to accept the default answers to all questions,
> unless you know what you're doing.
> 
> Some south bridges, CPUs or memory controllers contain embedded sensors.
> Do you want to scan for them? This is totally safe. (YES/no): yes
> modprobe: FATAL: Module cpuid not found in directory /lib/modules/4.15.0-1048-raspi2
> Failed to load module cpuid.
> Silicon Integrated Systems SIS5595...                       No
> VIA VT82C686 Integrated Sensors...                          No
> VIA VT8231 Integrated Sensors...                            No
> AMD K8 thermal sensors...                                   No
> AMD Family 10h thermal sensors...                           No
> AMD Family 11h thermal sensors...                           No
> AMD Family 12h and 14h thermal sensors...                   No
> AMD Family 15h thermal sensors...                           No
> AMD Family 16h thermal sensors...                           No
> AMD Family 15h power sensors...                             No
> AMD Family 16h power sensors...                             No
> Intel digital thermal sensor...                             No
> Intel AMB FB-DIMM thermal sensor...                         No
> Intel 5500/5520/X58 thermal sensor...                       No
> VIA C7 thermal sensor...                                    No
> VIA Nano thermal sensor...                                  No
> 
> Lastly, we can probe the I2C/SMBus adapters for connected hardware
> monitoring devices. This is the most risky part, and while it works
> reasonably well on most systems, it has been reported to cause trouble
> on some systems.
> Do you want to probe the I2C/SMBus adapters now? (YES/no): yes
> Sorry, no supported PCI bus adapters found.
> 
> Next adapter: bcm2835 I2C adapter (i2c-1)
> Do you want to scan it? (YES/no/selectively): yes
> 
> Sorry, no sensors were detected.
> Either your system has no sensors, or they are not supported, or
> they are connected to an I2C or SMBus adapter that is not
> supported. If you find out what chips are on your board, check
> http://www.lm-sensors.org/wiki/Devices for driver status.

**Comment by TheRemote** [comment]
This package does not work on Pi.  Alternatives are vcgencmd and you can also read /sys/class/thermal/thermal_zone0/temp and divide it by 1000 to get the temperature in Celsius

If anyone has actually got lm-sensors working I will gladly accept the patch but after a ton of research I have come up with nothing for this one but people saying to use vcgencmd or read the sensor directly.
