### ISSUE TITLE
bluetooth doesn't work on xubuntu (v7)

### ISSUE THREAD

**Issue by dragonlost** [TheRemote/Ubuntu-Server-raspi4-unofficial#28]
the blueman service is running but no bluetooth device detected by blueman.
Wifi 2.4 and 5ghz work fine.

I just install Xubuntu en v7 image on rpi4b 4go.

**Comment by TheRemote** [comment]
Hello, this fix will be integrated in v11 but you may grab the necessary bluetooth firmware file using the following command and then restart the Pi to fix it:

cd /lib/firmware/brcm
wget https://github.com/RPi-Distro/bluez-firmware/raw/master/broadcom/BCM4345C0.hcd

**Comment by TheRemote** [comment]
This has been fixed in v11
