### ISSUE TITLE
Error on apt-get upgrade

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [TheRemote/Ubuntu-Server-raspi4-unofficial#3]
I'm very unfamiliar with Linux as a OS so this may be expected behaviour.

Im using the v2 of the image released on Aug 31.

After I run sudo apt-get update && sudo apt-get upgrade after lots of lines get printed I get a bunch of messages shown in the attached photo

![WhatsApp Image 2019-09-02 at 14 26 41](https://user-images.githubusercontent.com/11945453/64114718-f837cc80-cd8d-11e9-835f-3cc440a254aa.jpeg)

I was getting a similar error when I ran v2 of the disk image so I guess its expected behaviour as you don't want the ubuntu firmware to update on this device?

**Comment by TheRemote** [comment]
Hey Chris, 

That's exactly right.  The firmware in the Ubuntu repository is unfortunately the firmware that does not contain RPI4 support (basically, flash-kernel replaces /boot/firmware with the version so it won't boot afterward).  Once Ubuntu updates it will be safe for flash-kernel to run again

**Comment by ChrisAllisonMalta** [comment]
Thanks @TheRemote , enjoy Labour day
