### ISSUE TITLE
Difficulty setting arm_freq

### ISSUE THREAD

**Issue by sam-wright** [TheRemote/Ubuntu-Server-raspi4-unofficial#35]
Using V8, I seem to be unable to specify the arm_freq. Has this functionality been moved elsewhere? 

I've tried recreating the old config.txt and making the appropriate changes, but they do not seem to be read in. Is there documentation for this that I'm missing?

**Comment by TheRemote** [comment]
Hey sam,

Are you editing /boot/firmware/config.txt instead of /boot/config.txt?  It's in a different location in Ubuntu

**Comment by sam-wright** [comment]
Ah thank you! I was indeed looking in the wrong place.
