### ISSUE TITLE
Wifi drivers missing

### ISSUE THREAD

**Issue by bruces22** [TheRemote/Ubuntu-Server-raspi4-unofficial#41]
Can not setup WiFi.  Was OK in V8...

**Comment by marksergeant** [comment]
I can confirm, the wlan adapter is not present in v9, v8 and raspbian are working as expected.

**Comment by TheRemote** [comment]
This is strange, I didn't change anything that should have affected the wireless in this version.  I'll start investigating as this will be a high priority fix.

**Comment by MadWomen** [comment]
i can confirm this aswell, also no bluetooth but that is probably a known issue and never worked to begin with.

**Comment by TheRemote** [comment]
Wireless is working again in v10, bluetooth I am still investigating but I wanted to get v10 out as fast as possible
