### ISSUE TITLE
bluetooth not working

### ISSUE THREAD

**Issue by phmatos** [TheRemote/Ubuntu-Server-raspi4-unofficial#43]
Hello the v11 system is not working the bluetooth adapter, i have a pi 4gb model

**Comment by darkhorseman45** [comment]
I have the same problem.. Same system raspberry pi4 4gig model. The bluetooth is not working installed kubuntu desktop everything went well. Wireless working youtube is great very snappy, but when i go to the bluetooth section it says adapter not found.

**Comment by darkhorseman45** [comment]
![Screenshot_20191005_160350](https://user-images.githubusercontent.com/56206615/66260857-cac5b080-e789-11e9-9040-6c40e8abd76c.png)

**Comment by darkhorseman45** [comment]
By the way saw all the work you did yesterday. I really appreciate you thank you for the hard work

**Comment by MadWomen** [comment]
can confirm, not working in v11

**Comment by TheRemote** [comment]
Hey everyone, thanks for the reports.  I swear I had this working but I was so excited about the video driver fix that apparently I did not test well enough!

I will investigate and report back!

**Comment by TheRemote** [comment]
I found it, can you try with v12?

**Comment by MadWomen** [comment]
bluetooth works now in v12, thank you for the quick fix!

**Comment by TheRemote** [comment]
No problem!
