### ISSUE TITLE
ssh file in boot directory

### ISSUE THREAD

**Issue by tgwaste** [TheRemote/Ubuntu-Server-raspi4-unofficial#45]
Does this not work here?

**Comment by TheRemote** [comment]
It should not be necessary for Ubuntu (it's on by default)

**Comment by tgwaste** [comment]
hmm everything looks like it boots, all lights flashing.. eth flashing but dont see it on the router.

**Comment by MadWomen** [comment]
i did notice that ssh wasn't working in v8 but it does work again after so i suggest you install the latest pre-release.
