### ISSUE TITLE
How can I use the CSI Raspberry Pi Camera

### ISSUE THREAD

**Issue by jensJJ** [TheRemote/Ubuntu-Server-raspi4-unofficial#48]
Thank you, I tested the newest build on the Rpi4 works good! I was trying to run the CSI camera, but cannot get it running using gstreamer, since it does not appear on video0 or any. Do you know how to fix this?

**Comment by TheRemote** [comment]
It sounds like that camera uses i2c.  In v13 I added raspi-config in which should help you get everything enabled.  Can you try with the latest release?

**Comment by jensJJ** [comment]
Hello, do I have to download the new build image or can I update dist on my current RPI4?

**Comment by TheRemote** [comment]
Right now you would need to download and reinstall, but the update feature is coming soon (TM).

No, but seriously, now that the fsck errors and hardware errors are under control I want to get the update script out in the next release or two!

As for the camera issue, it should be as easy as going into raspi-config and turning on the camera interface/drivers just like you would in something like Raspbian Lite.  If this gives you any trouble definitely reopen this issue and we can troubleshoot it further.
