### ISSUE TITLE
Feature request: Make cloud-init available from /boot

### ISSUE THREAD

**Issue by dkrizic** [TheRemote/Ubuntu-Server-raspi4-unofficial#51]
Hi TheRemote,

thanks for this great image. It runs multiple Kubernetes nodes in my hybrid Kubernetes cluster with Ceph volumes.

As you mentioned somewhere there is cloud-init already installed on this Ubuntu distribution. It would be great if cloud-init would pick up the configuration files from /boot/<somedir> at startup. That would allow to configure the machine fully via cloud-init.

**Comment by dkrizic** [comment]
The guys at Hypriot overwrite the cloud.cfg with this file:

https://github.com/hypriot/image-builder-rpi/blob/master/builder/files/etc/cloud/cloud.cfg so it will not try to contact any external servers. This would enable keeping cloud-init without delays on boot. I am currently investigating how they manage to read the configuration files from /boot

**Comment by damarshall** [comment]
@dkrizic you can also bootstrap your cluster using the nocloud method for `cloud-init`. I've documented the process [on this page](https://github.com/damarshall/rpi4utils/blob/master/docsite/content/docs/cloud-init/index.md). In essence, you create a *cidata* volume (type vfat) on a small external USB drive and insert that only for first boot. I use this method to bootstrap pi4 clusters.

Here's a link to a [directory with template cloud-init content](https://github.com/damarshall/rpi4utils/tree/master/cloud/seed).

You'll have to edit `meta-data` and `network-config` between boots of subsequent nodes in your cluster, and you have to bootstrap a node at a time but I've done it several times and can bring up a cluster of 8 nodes in about an hour, including imaging drives.

**Comment by dkrizic** [comment]
Nice one @damarshall , this sounds like a nice alternative approach!
