### ISSUE TITLE
AES hardware support

### ISSUE THREAD

**Issue by fabricemrchl** [TheRemote/Ubuntu-Server-raspi4-unofficial#53]
Hi,
Is-it possible to enable AES hardware support to improve dm-crypt and openvpn performance?
Thanks

**Comment by TheRemote** [comment]
This is already enabled in the current build (at least the generic forms).

Do you have a link to any documentation for flags or what should be set?

**Comment by TheRemote** [comment]
Closing unless other flags are brought forward for us to add to the kernel config
