### ISSUE TITLE
GNUradio performance question

### ISSUE THREAD

**Issue by keyboarderror** [TheRemote/Ubuntu-Server-raspi4-unofficial#54]
This may be beyond the scope of this project so please consider it a question. In trying out the GNUradio companion 3.7.11 GUI on the test builds the pre-release v10 works and performs very smoothly with close to desktop performance. By pre-release 12 the companion GUI has developed a significant hang up on scrolling the image of any larger flowgraph and the actual performance is unusable. This is ALSO the current state of operation in Raspbian Buster. So what changed? What needs to be fixed?

The raspberry pi 4 is quite good for GNUradio otherwise! Testing in v10. Thanks.

**Comment by TheRemote** [comment]
Hey keyboarderror,

I think I can shed some light on this.  In pre-release V12 we are using the /lib/firmware from Raspbian buster copied over the top of the existing Ubuntu firmware.  In V10 specifically we were only using the files released in the firmware-nonfree repository located at https://github.com/RPi-Distro/firmware-nonfree but this left a lot of devices in a non-working state.

This likely means that the version of firmware files that control devices being used by GNUradio have some sort of performance issue or bug in them (in the latest buster release) and that the original Ubuntu ones appear to be performing better.  

If possible find out which firmware files specifically might be getting used here.  These files are located in /lib/firmware.  It's easy to swap them out if other versions are working better.  If you have no idea which firmware files are actually in use here you can still swap "sets" of firmware.  

For example, if you find that the firmware from V10 is giving you the performance you need try creating a test image with the latest release and then copying the firmware from V10's "/lib/firmware" folder over the top of the V12 one.  After a restart compare performance within the GUI.

There is also another couple of possibilities I should mention in case you try a firmware swap and it doesn't affect the performance: kernel flags compiled into the kernel when it is built could be different (try comparing kernel flags from a good performing V10 image vs. a V12, and vs Raspbian), and another possibility is that a dependency has been updated in apt that is changing performance (if you have been updating your V10 image with apt-get update this is unlikely to be the reason).

**Comment by keyboarderror** [comment]
Thank you. I'll give this a try. I've got a few SDcards with different installations, I'll see what I can mix and match. If I find anything interesting I'll let you know!

**Comment by keyboarderror** [comment]
Well I renamed and copied the whole v10 firmware to v12 for the first test. It boots but had no effect on GRC. It's still very very sluggish. 
(It did help video playback on Kodi, so clearly it did something)
Hmm.

**Comment by keyboarderror** [comment]
If I'm looking at the right automatically generated config files at system-boot/config, it shows minor kernel flag changes when viewed with meld. Mostly defining parameters that were not previously set. I haven't found the equivalent file in Raspbian. The differences are much bigger when compared with the writable/boot/config-5.3.0-1007-raspi2 file in Ubuntu 19.10. There's also significant differences between the 32 and 64 bit 19.10. GRC is working properly on 32bit 19.10. I haven't been able to test 64bit due to a USB problem that prevents keyboard input or much beyond SSH. I will keep searching.

**Comment by TheRemote** [comment]
Hey keyboarderror,

They are constantly updating the kernel to fix issues like this.  Since my last release there had been 3 new kernel releases.

If you have time, would you try on v13?

**Comment by keyboarderror** [comment]
I've built a v13 image, but GRC still has a problem. Video is much better. Thanks.
Not to confuse things but 19.10's 64bit USB issue seems to be related to how much ram the pi has. as covered by https://bugs.launchpad.net/ubuntu/+source/linux-raspi2/+bug/1848790  
Checking workarounds there..

**Comment by keyboarderror** [comment]
19.10 latest updates did not fix USB, but the testing kernel offered by Hui Wang in the above link DOES. GRC is working properly in 19.10 64bit. Video performance is slow overall but it's a tentative success and a distinct woohoo.

**Comment by TheRemote** [comment]
It will continue to improve!  I'm downloading the 19.10 image to try right now and I'm very curious how it will hold up to some of the tests that have been done on this image (that took a lot of work to get it working that well!)

**Comment by TheRemote** [comment]
Yeah I'm seeing usb issues immediately in this release.

A whole bunch of:
usb 1-1: device descriptor read/64, error 18

so it looks like they still have some glitches to work out for now.

On the upside it looks like a bunch of things that never worked in older releases like apparmor, etc. have all been fixed up for the release.  It should be very good once they stabilize the kernel/firmware.

Have you by chance installed the latest "bootloader" firmware using sudo rpi-eeprom-update?  I'll give a shameless plug for my walkthrough here: https://jamesachambers.com/raspberry-pi-4-bootloader-firmware-updating-recovery-guide/

But basically the Pi 4 is the first Pi that has onboard firmware.  They call it the bootloader but we already know there's a little bit more to it than that.  One of the first bootloader updates they did lowered power usage and heat dramatically and I believe some of that was USB related as well.  It's definitely worth a try if you haven't updated yet (maybe even try the beta channel if you are adventurous)

**Comment by keyboarderror** [comment]
Absolutely. With maturity I think this platform has really great potential. I can see all the different parts working in different configurations. In time things will "connect the dots" so to speak. I really appreciate your efforts and those of everyone else. It's easy to forget how complicated these things can be when complaining about the bits that don't work.

Yes, I have a Raspbian image for rpi-eeprom-update as you suggested. It says up to date as of 10th September 2019. I might try the beta once I understand how to recover.

I'm wondering if GRC is still not video related somehow. In which case it may happen in 19.10 as drivers evolve. If it's known anywhere previously that would help. And should you have any more test builds or patches I'm happy to try them.

**Comment by keyboarderror** [comment]
It's the accelerated video driver.
Comment out dtoverlay=vc4-fkms-v3d in config.txt as a work around.
