### ISSUE TITLE
How to enable Ad-Hoc mode ?

### ISSUE THREAD

**Issue by UmithanGoktolga** [TheRemote/Ubuntu-Server-raspi4-unofficial#56]
Hi all,

I am facing troubles while configuring ad-hoc mode, is there anyone try and succeed it ?

Thanks !

**Comment by TheRemote** [comment]
This is going to depend on how you are configuring your networking.

Is this in Ubuntu Desktop or are you in the original server mode still?  Are you using netplan or are you using other utilities to configure it?

This doc should get you on the right track: https://help.ubuntu.com/community/WifiDocs/Adhoc

It's specific to Ubuntu's available networking providers and all of these methods will work.
