### ISSUE TITLE
Release Updater

### ISSUE THREAD

**Issue by bruces22** [TheRemote/Ubuntu-Server-raspi4-unofficial#59]
Issue with Updater.sh.  Tried on V14, attached pic for details.
(Also still trying Boot with ssd)
![(rel)_Pic](https://user-images.githubusercontent.com/39317520/67703416-9f8d4600-f970-11e9-923d-73d71e2bc560.jpg)

**Comment by six4m** [comment]
Same Problem here !

**Comment by TheRemote** [comment]
I'm a dummy and put a code grouping in the wrong place!

Can you both redownload and try again?

**Comment by tikiatsbme** [comment]
Currently running Raspbian 32Bit as it works.

Here the /var/log/syslog file contents when it stopped working. 

[syslog.logfile.txt](https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial/files/3780719/syslog.logfile.txt)

[syslog.logfile.txt](https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial/files/3780726/syslog.logfile.txt)

**Comment by six4m** [comment]
now its working, thanks and all thumbs up your great work  :)

**Comment by TheRemote** [comment]
Thanks!
