### ISSUE TITLE
Nonvisible GUI (KDE Plasma?)

### ISSUE THREAD

**Issue by mrystrand** [TheRemote/Ubuntu-Server-raspi4-unofficial#6]
Just got this installed and understand this is not officially supported.
However, I am experiencing some quite major issues with the GUI.
In the attached screenshot you can see the start menu for Kubuntu.
Running on a RPi4 4GB with nothing else connected than USB keyboard, mouse and an HDMI display.

Anything I can do to improve or resolve this?

<img width="1097" alt="screenshot" src="https://user-images.githubusercontent.com/54815666/64294075-43103a80-cf6e-11e9-8415-c14219ac9268.png">

**Comment by TheRemote** [comment]
Hmmm, we need to get some log files for this.  It's probably not going to be that hard to fix once we know what is going wrong.

What you could do is get the logs off the SD card by plugging it into your computer and going to /var/log/ which should contain the information we need.

**Comment by TheRemote** [comment]
This has been fixed in v6
