### ISSUE TITLE
Raspberry Pi 4B_4GB failed install with release V15 Public

### ISSUE THREAD

**Issue by tikiatsbme** [TheRemote/Ubuntu-Server-raspi4-unofficial#60]
I xzcat the V15 XZ file, then I DD burned the V15 IMG file to a 32GB SanDisk Ultra. Shut down to RPi4B, inserted to micro sd card and turned it on. It booted for about 47.11 seconds until it got 3 lines pass "----END SSH HOST KEYS ---" and stopped dead in its tracks with flashing "_" underline symbol. 

No response from keyboard. Tried Ctrl-C and Return/Enter with no success. Had to shutoff pi and pull card which is on my desk. Any log file I should upload for trouble shooting??

I tried this with the stock Ubuntu 19.10 Arm64 and got similar results which itself is interesting, possible unrelated.

UPDATE: 20191029_1612 to 2243 hrs. 
Its has booted up twice. Installed desktop. Crashed once due to USB and keyboard not working, worked fine after reboot (Just reboot, it will fix everything). USB mouse, keyboard, sd card reader and 3 USB flash drive recognized. Had sound on initial upgrade (audio to audio only, no HDMI), now on 2nd or 3d reboot - sound sound. Will try to fix /boot/config.txt and try reboot again. Well its pretty stable, few glitches, getting there (V15 public release).

**Comment by TheRemote** [comment]
/var/log/syslog would be good

The SSH keys part is a part of the cloud-init stuff but it doesn't necessarily mean it is what is locking it up.

Does Raspbian boot on it?

**Comment by tikiatsbme** [comment]
,Using raspian 32Bit right now


Thomas J Killeen, PE (MA & NH), ME RMS #351
I-Phone: 207-752-4102
thomas.killeen@icloud.com
46 Woodland Hills
South Berwick, ME 03908-1834
Sent from iCloud

On October 28, 2019 at 5:04 PM, "James A. Chambers" <notifications@github.com> wrote:



/var/log/syslog would be good

The SSH keys part is a part of the cloud-init stuff but it doesn't necessarily mean it is what is locking it up.

Does Raspbian boot on it?

**Comment by tikiatsbme** [comment]
Currently running Raspbian 32Bit as it works.

Here the /var/log/syslog file contents when it stopped working.

[syslog.logfile.txt](https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial/files/3780733/syslog.logfile.txt)

**Comment by TheRemote** [comment]
Can you try unplugging all of those USB devices and booting for a test?

**Comment by tikiatsbme** [comment]
I tried it with all USB devices removed, that is keyboard, mouse, usb hub and usb flashdrive removed, got as far as login that required use of keyboard. Plugged in USB keyboard (mac 108 kybd) - not recognized. 

[syslog.logfile.txt](https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial/files/3781004/syslog.logfile.txt)

**Comment by boxlady** [comment]
Might be this? 
https://bugs.launchpad.net/ubuntu/+source/linux-raspi2/+bug/1848703
Try putting this in the config.txt
total_mem=3072

**Comment by TheRemote** [comment]
This should be working again in V16, let us know if you're still having issues!
