### ISSUE TITLE
Upgrade Script

### ISSUE THREAD

**Issue by charles-d-burton** [TheRemote/Ubuntu-Server-raspi4-unofficial#63]
Not sure why this error happens as the script seems to run to completion.  But, it does this.  Pi came back after reboot, was able to reproduce on three separate pis.  They all have 64GB SD cards that are relatively empty(they're just k3s nodes).

```bash
Extracting update package - This can take several minutes on the Pi ...
xz: (stdin): Unexpected end of input
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by TheRemote** [comment]
Fixed in v16, thanks for the report!
