### ISSUE TITLE
ubuntu-18.04.3-preinstalled-server-arm64+raspi4.img Failed 3 lines after "-END of Host Key Keys-"

### ISSUE THREAD

**Issue by tikiatsbme** [TheRemote/Ubuntu-Server-raspi4-unofficial#72]
UPDATE: try 2 with V20 on 11/7/2019, prior try was V18 on 11/4/2019.

Hi, I tried again with V18 on 11/3/2019 as well as v20  on 11/7/2019) as ubuntu-18.04.3-preinstalled-server-arm64+raspi4.img
(Compressed: 363.4 MB, expanded: 3.1 GB).   I Did:

sufo apt-get install git
git clone https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial
download V18 - current 20191104
archiver to expand image
run gparted and format micro sd to fat 32
sudo dd bs=4M if=file.img of=/dev/sdd status=progress conv=fsynce
copy some files to HOME file on sdd
copy directory
sudo rsync -av /someplaceold/piclone /someplacenew/piclone
Shutdown, switch cards, start Rpi4B_4GB

#### ERROR ###### SAME error 2x 
Failed to continue  3 lines after "-END of Host Key Keys-"
2nd line said:  ci-info, no authorized ssh keys fingerprints found for user ubuntu

V18: /var/log/syslog file to attached. The attached syslog (syslog.log) shows some 28 lines of code, all I saw was a flashing light.

V20: 20191107V20syslog.log attached. 20191107V20syslog.log show some 32 lines after and it ran for 2:17 hrs. What is up with my pi4B_4GB?????????

[20191107V20syslog.log](https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial/files/3824020/20191107V20syslog.log)

[syslog.log](https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial/files/3806262/syslog.log)

**Comment by TheRemote** [comment]
Sorry I have been slow to answer this, I have been busy.  I'd like to suggest an alternate approach of mounting the image to do this:

```
sudo apt install kpartx
MountCheck=$(sudo kpartx -avs "file.img")
echo "$MountCheck"
export MOUNT_IMG=$(echo "$MountCheck" | awk 'NR==1{ print $3 }')
export MOUNT_IMG="${MOUNT_IMG%p1}"
sudo mount "/dev/mapper/${MOUNT_IMG}p2" /mnt
sudo mount "/dev/mapper/${MOUNT_IMG}p1" /mnt/boot/firmware
```

The image is now mounted.  If you go to cd /mnt it will be the whole image.  Now copy piclone over:

```
sudo rsync -av /someplaceold/piclone /mnt/usr/bin/piclone

```

When you are finished copying everything you want to on the image close it like this:

```
sudo umount /mnt/boot/firmware
sudo umount /mnt
sudo kpartx -dvs "file.img"
```

Now you can burn the file.img normally with dd.  Try this way and see if the boot errors go away!

**Comment by tikiatsbme** [comment]
I will try a CLEAN git clone and a clean DD, let it boot to curser. I have been altering image, ooops, sorry, learning fast though.
