### ISSUE TITLE
ssh server host keys are missing

### ISSUE THREAD

**Issue by ozhankaraman** [TheRemote/Ubuntu-Server-raspi4-unofficial#77]
When i try to ssh to release v20 server i noticed that ssh host keys are missing so ssh service does not allow incoming connections. 

pi@pi4:/etc/ssh$ ls -l
total 556
-rw-r--r-- 1 root root 553122 Mar  4  2019 moduli
-rw-r--r-- 1 root root   1580 Mar  4  2019 ssh_config
-rw------- 1 root root      0 Jan 28  2018 ssh_host_dsa_key
-rw-r--r-- 1 root root      0 Jan 28  2018 ssh_host_dsa_key.pub
-rw------- 1 root root      0 Jan 28  2018 ssh_host_ecdsa_key
-rw-r--r-- 1 root root      0 Jan 28  2018 ssh_host_ecdsa_key.pub
-rw------- 1 root root      0 Jan 28  2018 ssh_host_ed25519_key
-rw-r--r-- 1 root root      0 Jan 28  2018 ssh_host_ed25519_key.pub
-rw------- 1 root root      0 Jan 28  2018 ssh_host_rsa_key
-rw-r--r-- 1 root root      0 Jan 28  2018 ssh_host_rsa_key.pub
-rw-r--r-- 1 root root    338 Aug  5 20:04 ssh_import_id
-rw-r--r-- 1 root root   3263 Jan 28  2018 sshd_config

root@pi4:/var/log# tail -f auth.log 
Nov  8 21:08:43 pi4 sshd[2790]: error: key_load_private: invalid format
Nov  8 21:08:43 pi4 sshd[2790]: error: key_load_public: invalid format
Nov  8 21:08:43 pi4 sshd[2790]: error: Could not load host key: /etc/ssh/ssh_host_rsa_key
Nov  8 21:08:43 pi4 sshd[2790]: error: key_load_private: invalid format
Nov  8 21:08:43 pi4 sshd[2790]: error: key_load_public: invalid format
Nov  8 21:08:43 pi4 sshd[2790]: error: Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Nov  8 21:08:43 pi4 sshd[2790]: error: key_load_private: invalid format
Nov  8 21:08:43 pi4 sshd[2790]: error: key_load_public: invalid format
Nov  8 21:08:43 pi4 sshd[2790]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key
Nov  8 21:08:43 pi4 sshd[2790]: fatal: No supported key exchange algorithms [preauth]

To solve the issue i delete ssh keys and regenerate them.

root@pi4:~# rm -f /etc/ssh/ssh_host_*
root@pi4:~# ssh-keygen -A
ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519 
root@pi4:~# ls -l /etc/ssh
total 588
-rw-r--r-- 1 root root 553122 Mar  4  2019 moduli
-rw-r--r-- 1 root root   1580 Mar  4  2019 ssh_config
-rw------- 1 root root    672 Nov  8 21:15 ssh_host_dsa_key
-rw-r--r-- 1 root root    616 Nov  8 21:15 ssh_host_dsa_key.pub
-rw------- 1 root root    227 Nov  8 21:15 ssh_host_ecdsa_key
-rw-r--r-- 1 root root    188 Nov  8 21:15 ssh_host_ecdsa_key.pub
-rw------- 1 root root    419 Nov  8 21:15 ssh_host_ed25519_key
-rw-r--r-- 1 root root    108 Nov  8 21:15 ssh_host_ed25519_key.pub
-rw------- 1 root root   1675 Nov  8 21:15 ssh_host_rsa_key
-rw-r--r-- 1 root root    408 Nov  8 21:15 ssh_host_rsa_key.pub
-rw-r--r-- 1 root root    338 Aug  5 20:04 ssh_import_id
-rw-r--r-- 1 root root   3263 Jan 28  2018 sshd_config
root@pi4:~# systemctl restart ssh
root@pi4:~#

**Comment by TheRemote** [comment]
This was netplan related -- fixed in v21
