### ISSUE TITLE
USB boot

### ISSUE THREAD

**Issue by freewill404** [TheRemote/Ubuntu-Server-raspi4-unofficial#81]
Can this image be used for [USB boot](https://jamesachambers.com/raspberry-pi-4-usb-boot-config-guide-for-ssd-flash-drives/) on the Pi4, and if yes, should it be 2 x Ubuntu 18.04.3 on both the Micro SD and the SSD, or we can use the Raspbian Buster Lite as a bootloader on the Micro SD?

**Comment by TheRemote** [comment]
Hey freewill404,

Absolutely!  I did this yesterday and did 2x Ubuntu 18.04.3 on both the SD card and the SSD and then you will make the following change to /boot/firmware/cmdline.txt (or if you insert the card into your PC cmdline.txt inside the "boot" partition):

`snd_bcm2835.enable_headphones=1 snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_compat_alsa=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 fsck.repair=yes fsck.mode=auto root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait`

Change root device as follows:

`snd_bcm2835.enable_headphones=1 snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_compat_alsa=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 fsck.repair=yes fsck.mode=auto root=/dev/sda2 rootfstype=ext4 elevator=deadline rootwait`

That's all I had to do and I booted up from the SSD!  Note that the password will reset back to ubuntu/ubuntu after a successful switchover to SSD (this is a good indicator that everything switched over correctly).
