### ISSUE TITLE
apparmor module is not loaded

### ISSUE THREAD

**Issue by deltasierra-ufc** [TheRemote/Ubuntu-Server-raspi4-unofficial#89]
Using v22 release, fairly fresh install.

This is what I get when I submit 

> sudo apparmor_status

> apparmor module is not loaded

I've gone thru the Ubuntu apparmor wiki, starting the service, making sure I have apparmor, apparmor_utils, and apparmor_profiles installed.  Running 

> sudo modprobe appmor

 results in 

> FATAL: Module apparmor not found in directory /lib/modules/4.19.83-v8-22

How can I enable the apparmor module?  I also had issues trying to run Firefox and other apps with firejail installed -- could this be the reason why?

**Comment by TheRemote** [comment]
Possibly, I have experimented with enabling AppArmor in the kernel before, I will enable it for the next build then let's check

**Comment by TheRemote** [comment]
Fixed in v23

**Comment by deltasierra-ufc** [comment]
Ok, awesome!  Thank you James.
