### ISSUE TITLE
RDB is missing (was Ceph is missing)

### ISSUE THREAD

**Issue by dkrizic** [TheRemote/Ubuntu-Server-raspi4-unofficial#9]
Hi, 

thank you very much for the kernel with Ceph, but unfortunately RDB is still not supported. My rook-ceph-agent reports:

2019-09-07 19:50:07.898118 I | exec: Running command: modprobe rbd
2019-09-07 19:50:07.905521 I | modprobe rbd: modprobe: FATAL: Module rbd not found.

I thought, that RBD is part of Ceph, and I can see that Ceph is in the Kernel, but RBD is not.

**Comment by dkrizic** [comment]
Some documentations are stating, that rbd should be part of the kernel as of 4.x. I am confused.

**Comment by dkrizic** [comment]
From rook-ceph documentation:

Re-configure your kernel to make sure the CONFIG_BLK_DEV_RBD=y in the .config file, then build the kernel.

https://github.com/rook/rook/blob/master/Documentation/ceph-common-issues.md#rook-agent-rbd-module-missing-error

**Comment by charles-d-burton** [comment]
I'm seeing the same issue.

**Comment by TheRemote** [comment]
Thank you, this helps a lot since I didn't know exactly what this was but that link tells me everything I need!

**Comment by dkrizic** [comment]
A little background what I am doing: I have a Kubernetes cluster on bare-bone APU2C4 boards (amd64, 4 cores, low power). Each of these boards have a 500GB SSD card. 100GB is used for the OS, 400 for Ceph. I run Kubernetes 1.15.3 with Calico networking.

I run rook-ceph on the cluster that provides redundant storage; so the cluster is self converged.

I would like to extend this cluster with a few Raspberry Pi 4 nodes. Meanwhile a lot of things are working:

- [x] Calico CNI daemonset runs (they have an arm64 image)
- [x] Rook Ceph Discovery runs
- [ ] Rook Ceph Agent does not run since it requires RBD kernel module

With the next kernel that includes RBD the Rook Ceph Agent should start and be able to mount Ceph volumes on the Raspi nodes.

**Comment by dkrizic** [comment]
When is the next run/release expected?

**Comment by TheRemote** [comment]
I've committed this in v7, can someone give it a try?

**Comment by dkrizic** [comment]
Testing

**Comment by dkrizic** [comment]
RBD is here! rook-ceph starts. Thanks!

State: I am unable to mount volumes to the Raspi node (which does not provide any storage, just consumes), but this seems to be a rook-ceph/Ceph specific problem.

**Comment by dkrizic** [comment]
One observation: The fan of the HAT does not run anymore... I should have run long ago... I don't know if this has to do with the kernel.
