### ISSUE TITLE
Not working I2C-0 when camera enabled

### ISSUE THREAD

**Issue by michal-stolarz** [TheRemote/Ubuntu-Server-raspi4-unofficial#93]
I tried to use i2c-0 with enabled camera interface (with raspi-config). Unfortunately i2c-0 doesn't detect any devices.

**Comment by TheRemote** [comment]
Sounds like this issue to me: https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial/issues/87

Have you added the following to /boot/firmware/config.txt:

dtparam=i2c1=on
dtparam=i2c0=on

**Comment by michal-stolarz** [comment]
Yes of course I tried. When I turn off camera both i2c work. But when I turn on then i2c-0 can't detect any devices.

**Comment by TheRemote** [comment]
This is a tricky one for me because I don't have the camera module.  Maybe I will pick one up as they look pretty cheap.

Which camera module do you have?  Do you have the official Raspberry Pi one?  If so is it the V2 one or the V1?

**Comment by michal-stolarz** [comment]
I have Waveshare Camera G OV5647, v1. Yes, it is official.
