### ISSUE TITLE
HDMI audio - only buzzing sound

### ISSUE THREAD

**Issue by vondrt4** [TheRemote/Ubuntu-Server-raspi4-unofficial#94]
I've got a problem with HDMI audio. In the settings, I get two outputs, "Analog output" and "Analog Headphones". The first one is evidently the HDMI output, because when any sound is played, the TV makes clicking and buzzing sounds. I have tried various config.txt options to no avail. The same goes for changing between HDMI 0 and 1. LibreELEC, Raspbian and Raspbian with 64 bit kernel all work fine. Diagnostic output looks reasonable:
`
root@ubuntu:~# tvservice -s
state 0xa [HDMI CUSTOM RGB full unknown AR], 1360x768 @ 60.00Hz, progressive
root@ubuntu:~# tvservice -a
     PCM supported: Max channels: 2, Max samplerate:  48kHz, Max samplesize 24 bits.
     AC3 supported: Max channels: 6, Max samplerate:  48kHz, Max rate  640 kb/s.
root@ubuntu:~# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
`

**Comment by TheRemote** [comment]
Hey vondrt4,

I have an experiment for you to try.  Can you try removing the first 3 (audio related) options from /boot/cmdline.txt?
