### ISSUE TITLE
The WIFI 5G seems not stable on the v26 Release  ubuntu preinstalled desktop img

### ISSUE THREAD

**Issue by haomingLZ** [TheRemote/Ubuntu-Server-raspi4-unofficial#98]
I was using ssh to connect raspberry pi4 without a screen, it seems unstable with 5g wifi and was disconnected after a couple of minutes and can not be connected automatically again.
The problem solved when I change to connect 2.4G wifi.

**Comment by 3wnbr1** [comment]
Have you stumbled upon the same issue on Raspbian ? 5Ghz Wifi is known to be very picky especially at long range.

**Comment by TheRemote** [comment]
It's also possible that you are in a different country than the US and need to update your regulatory country (5Ghz needs this to know the right bands to use).  

This can be changed by editing /etc/default/crda and changing US to the code for your country.

**Comment by TheRemote** [comment]
If anyone is having issues still on v28 please open an issue!

**Comment by mcl21014** [comment]
I have WiFI issues as well, and noticed turning off power saving for WiFi somehow toggles on airplane mode, thus making it useless for troubleshooting, sadly. I've opened a new ticket.
